######################################################################
# Automatically generated by qmake (3.0) ?? 5? 3 22:58:36 2019
######################################################################

QT += widgets
TEMPLATE = app
TARGET = Hello
INCLUDEPATH += .

# Input
SOURCES += Hello.cpp
